-- MySQL Script generated by MySQL Workbench
-- Sun Jun 23 16:30:58 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS integracaoBD;
USE integracaoBD;


-- -----------------------------------------------------
-- Table `mydb`.`Efeito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Efeito` (
  `nome_id` VARCHAR(45) NOT NULL,
  `dano_extra` INT NULL,
  `velocidade_extra` INT NULL,
  PRIMARY KEY (`nome_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Arma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Arma` (
  `nome_id` VARCHAR(45) NOT NULL,
  `dano` INT NULL,
  `alcance` INT NULL,
  `velocidade` INT NULL,
  `knockback` INT NULL,
  `Efeito_nome_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nome_id`),
  INDEX `fk_Arma_Efeito1_idx` (`Efeito_nome_id` ASC) VISIBLE,
  CONSTRAINT `fk_Arma_Efeito1`
    FOREIGN KEY (`Efeito_nome_id`)
    REFERENCES `mydb`.`Efeito` (`nome_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Habilidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Habilidade` (
  `nome_ID` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NULL,
  `dano` INT NULL,
  `velocidade` INT NULL,
  `cooldown` INT NULL,
  `efeito` VARCHAR(45) NULL,
  `Efeito_nome_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nome_ID`, `Efeito_nome_id`),
  INDEX `fk_Habilidade_Efeito1_idx` (`Efeito_nome_id` ASC) VISIBLE,
  CONSTRAINT `fk_Habilidade_Efeito1`
    FOREIGN KEY (`Efeito_nome_id`)
    REFERENCES `mydb`.`Efeito` (`nome_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Efeito-Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Efeito-Item` (
  `nome_id` VARCHAR(45) NOT NULL,
  `Efeito-Itemcol` VARCHAR(45) NULL,
  `??` VARCHAR(45) NULL,
  PRIMARY KEY (`nome_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Item` (
  `nome_id` VARCHAR(45) NOT NULL,
  `efeito` VARCHAR(45) NOT NULL,
  `consumivel` INT NULL,
  `Efeito-Item_nome_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nome_id`, `Efeito-Item_nome_id`),
  INDEX `fk_Item_Efeito-Item1_idx` (`Efeito-Item_nome_id` ASC) VISIBLE,
  CONSTRAINT `fk_Item_Efeito-Item1`
    FOREIGN KEY (`Efeito-Item_nome_id`)
    REFERENCES `mydb`.`Efeito-Item` (`nome_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Personagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Personagem` (
  `nome_id` VARCHAR(45) NULL,
  `nivel` INT NULL,
  `vida` INT NULL,
  `força` INT NULL,
  `tipo` VARCHAR(45) NULL,
  `Arma_nome_id` VARCHAR(45) NOT NULL,
  `Habilidade_nome_ID` VARCHAR(45) NOT NULL,
  `Item_nome_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nome_id`, `Arma_nome_id`),
  INDEX `fk_Personagem_Arma1_idx` (`Arma_nome_id` ASC) VISIBLE,
  INDEX `fk_Personagem_Habilidade1_idx` (`Habilidade_nome_ID` ASC) VISIBLE,
  INDEX `fk_Personagem_Item1_idx` (`Item_nome_id` ASC) VISIBLE,
  CONSTRAINT `fk_Personagem_Arma1`
    FOREIGN KEY (`Arma_nome_id`)
    REFERENCES `mydb`.`Arma` (`nome_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Personagem_Habilidade1`
    FOREIGN KEY (`Habilidade_nome_ID`)
    REFERENCES `mydb`.`Habilidade` (`nome_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Personagem_Item1`
    FOREIGN KEY (`Item_nome_id`)
    REFERENCES `mydb`.`Item` (`nome_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
